
import React, { useState, useRef, useEffect } from 'react';
import { IdCardFront, IdCardBack, BCAgentCard, BCAgentCardBack } from './components/IdCard';
import { InputGroup } from './components/InputGroup';
import { DisclaimerModal } from './components/DisclaimerModal';
import { PublicProfile } from './components/PublicProfile';
import { AdminPanel } from './components/AdminPanel';
import { IdCardData, INITIAL_ID_DATA } from './types';
import { generateIdentityData } from './services/geminiService';
import { savePublicCard, getCardById, isConfigValid } from './services/supabase';
import { Sparkles, RefreshCw, Printer, Tractor, Save, FolderOpen, LayoutDashboard, Settings, Menu, Image as ImageIcon, Trash2, Download, PenTool, X, Camera, Lock, UserCircle } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from "jspdf";

export default function App() {
  // --- STATE ---
  const [view, setView] = useState<'create' | 'admin' | 'verify'>('create');
  
  // Data State
  const [data, setData] = useState<IdCardData>(INITIAL_ID_DATA);
  const [publicData, setPublicData] = useState<IdCardData | null>(null);
  
  // UI State
  const [activeTab, setActiveTab] = useState<'manual' | 'auto'>('manual');
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [prompt, setPrompt] = useState('');
  
  // Loading States
  const [isLoading, setIsLoading] = useState(false); // Gemini
  const [isSaving, setIsSaving] = useState(false); // Supabase
  const [isDownloading, setIsDownloading] = useState(false); // PDF

  // Refs
  const fileInputRef = useRef<HTMLInputElement>(null);
  const signatureInputRef = useRef<HTMLInputElement>(null);
  const logoInputRef = useRef<HTMLInputElement>(null);

  // --- INITIALIZATION ---
  useEffect(() => {
    // Check URL for ?id= (Verification Mode)
    const params = new URLSearchParams(window.location.search);
    const cardId = params.get('id');

    if (cardId) {
      setView('verify');
      setIsLoading(true);
      getCardById(cardId).then((card) => {
        if (card) {
          setPublicData(card);
        } else {
          alert("Card not found or ID is invalid.");
          setView('create');
        }
        setIsLoading(false);
      });
    }
  }, []);

  // --- HANDLERS ---

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setData(prev => ({ ...prev, [name]: value }));
  };

  // Generic File Uploader
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>, field: 'photoUrl' | 'signatureUrl' | 'logoUrl') => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setData(prev => ({ ...prev, [field]: reader.result as string }));
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAutoGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    try {
      const generatedData = await generateIdentityData(prompt);
      // Keep cardType, but overwrite fields
      setData(prev => ({ ...prev, ...generatedData, id: undefined, cardType: prev.cardType }));
    } catch (error) {
      alert("AI Generation failed. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveCard = async () => {
    if (!data.name || !data.idNumber) {
      alert("Please fill at least Name and Former ID (ID Number) before saving.");
      return;
    }

    setIsSaving(true);
    try {
      // Public Save (Anonymous)
      const newId = await savePublicCard(data);
      
      // Update local state with the new ID so QR code updates immediately
      const updatedData = { ...data, id: newId };
      setData(updatedData);
      
      alert(`Record Saved Successfully!\n\nSystem ID: ${newId}\n\nThe QR Code is now active. You can now download or print.`);
    } catch (e) {
      alert("Error saving card.");
      console.error(e);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDownloadPDF = async () => {
    const frontElement = document.getElementById('card-front');
    const backElement = document.getElementById('card-back');

    if (!frontElement || !backElement) {
      alert("Could not find card elements.");
      return;
    }

    setIsDownloading(true);

    try {
      const canvasFront = await html2canvas(frontElement, { scale: 4, useCORS: true, backgroundColor: null });
      const canvasBack = await html2canvas(backElement, { scale: 4, useCORS: true, backgroundColor: null });

      const pdf = new jsPDF('p', 'mm', 'a4');
      pdf.setFontSize(10);
      pdf.text("Front Side:", 15, 13);
      pdf.addImage(canvasFront.toDataURL('image/png'), 'PNG', 15, 15, 85.6, 54);

      pdf.text("Back Side:", 15, 80);
      pdf.addImage(canvasBack.toDataURL('image/png'), 'PNG', 15, 82, 85.6, 54);

      pdf.setFontSize(8);
      pdf.setTextColor(150);
      pdf.text("Generated by KisanID Public Portal", 15, 280);

      pdf.save(`${data.name.replace(/\s+/g, '_')}_Card.pdf`);
    } catch (error) {
      console.error("PDF Fail", error);
      alert("Failed to generate PDF.");
    } finally {
      setIsDownloading(false);
    }
  };

  // --- RENDER VIEWS ---

  if (view === 'verify') {
    if (!publicData) return <div className="h-screen flex items-center justify-center bg-slate-100">Loading Record...</div>;
    return (
        <div className="relative">
             <button 
                onClick={() => setView('create')} 
                className="fixed top-4 right-4 z-50 bg-black/50 text-white px-4 py-2 rounded-full text-xs font-bold backdrop-blur-md hover:bg-black/70"
             >
                Create Your Own Card
             </button>
            <PublicProfile data={publicData} />
        </div>
    );
  }

  if (view === 'admin') {
      return <AdminPanel onLogout={() => setView('create')} />;
  }

  // --- MAIN DASHBOARD (CREATE MODE) ---
  return (
    <div className="h-screen w-screen bg-slate-900 flex overflow-hidden font-sans text-slate-900">
      <DisclaimerModal />

      {/* MOBILE OVERLAY */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-40 md:hidden"
          onClick={() => setIsSidebarOpen(false)}
        ></div>
      )}

      {/* SIDEBAR */}
      <div className={`fixed inset-y-0 left-0 w-[280px] bg-slate-900 text-slate-300 flex flex-col border-r border-slate-800 print:hidden z-50 shadow-xl transition-transform duration-300 md:translate-x-0 md:static ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        {/* Brand */}
        <div className="h-16 flex items-center gap-3 px-5 border-b border-slate-800 bg-slate-950">
           <div className="w-8 h-8 bg-green-600 rounded-md flex items-center justify-center text-white shadow-lg">
              <Tractor size={18} />
           </div>
           <div className="flex-1">
             <h1 className="text-white font-bold text-lg">KisanID Public</h1>
             <p className="text-[10px] text-slate-500 font-semibold">Free Generator Tool</p>
           </div>
           <button onClick={() => setIsSidebarOpen(false)} className="md:hidden text-slate-500">
             <X size={20} />
           </button>
        </div>

        {/* Navigation */}
        <div className="flex-1 py-6 px-3 space-y-1 overflow-y-auto custom-scrollbar">
           
           <div className="px-3 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Card Template</div>
           <div className="grid grid-cols-2 gap-2 mb-6 px-1">
              <button 
                onClick={() => setData(prev => ({...prev, cardType: 'kisan'}))}
                className={`flex flex-col items-center justify-center p-2 rounded-lg border transition-all ${data.cardType === 'kisan' ? 'bg-green-900/30 border-green-600 text-green-400' : 'border-slate-700 hover:bg-slate-800 text-slate-400'}`}
              >
                 <Tractor size={20} className="mb-1" />
                 <span className="text-[10px] font-bold">Kisan ID</span>
              </button>
              <button 
                onClick={() => setData(prev => ({...prev, cardType: 'bc_agent'}))}
                className={`flex flex-col items-center justify-center p-2 rounded-lg border transition-all ${data.cardType === 'bc_agent' ? 'bg-blue-900/30 border-blue-600 text-blue-400' : 'border-slate-700 hover:bg-slate-800 text-slate-400'}`}
              >
                 <PenTool size={20} className="mb-1" />
                 <span className="text-[10px] font-bold">BC Agent</span>
              </button>
           </div>

           <div className="px-3 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Data Input</div>
           
           <button onClick={() => { setActiveTab('manual'); setIsSidebarOpen(false); }} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all ${activeTab === 'manual' ? 'bg-green-600/10 text-green-400 border border-green-600/20' : 'hover:bg-slate-800 hover:text-white'}`}>
              <LayoutDashboard size={18} />
              Manual Entry
           </button>
           
           <button onClick={() => { setActiveTab('auto'); setIsSidebarOpen(false); }} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all ${activeTab === 'auto' ? 'bg-purple-600/10 text-purple-400 border border-purple-600/20' : 'hover:bg-slate-800 hover:text-white'}`}>
              <Sparkles size={18} />
              AI Auto-Fill
           </button>

           <div className="px-3 mt-8 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Actions</div>
           
           <button 
             disabled={isSaving}
             onClick={handleSaveCard}
             className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium hover:bg-slate-800 hover:text-white transition-all text-white bg-green-700 shadow-md mb-2"
           >
              {isSaving ? <RefreshCw className="animate-spin" size={18} /> : <Save size={18} />}
              {isSaving ? 'Saving...' : 'Save & Generate QR'}
           </button>

           <div className="mt-4 p-3 bg-slate-800 rounded-lg border border-slate-700">
               <p className="text-[10px] text-slate-400 mb-2">Save required to activate QR code.</p>
           </div>
        </div>

        {/* Footer / Admin Link */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/50 flex justify-between items-center">
            <div className="flex items-center gap-2">
                 <UserCircle className="text-slate-600" size={16} />
                 <span className="text-xs text-slate-500">Public User</span>
            </div>
            <button 
              onClick={() => setView('admin')}
              className="text-[10px] text-slate-600 hover:text-red-500 flex items-center gap-1 transition-colors"
            >
                <Lock size={10} /> Admin
            </button>
        </div>
      </div>

      {/* MAIN CONTENT AREA */}
      <div className="flex-1 flex flex-col h-full bg-gray-50 overflow-hidden relative">
        
        {/* Top Header */}
        <div className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 md:px-6 shadow-sm z-20 print:hidden shrink-0">
            <div className="flex items-center gap-4 text-gray-500">
               <button onClick={() => setIsSidebarOpen(true)} className="md:hidden text-gray-700 hover:bg-gray-100 p-2 rounded">
                  <Menu size={20} />
               </button>
               <span className="font-bold text-gray-800 text-sm md:text-lg">KisanID & Agent Card Generator</span>
            </div>
            <div className="flex items-center gap-2">
                <span className="text-[10px] bg-green-100 text-green-800 px-2 py-1 rounded font-bold uppercase flex items-center gap-1">
                   Public Mode
                </span>
            </div>
        </div>

        {/* Workspace */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
            
            {/* Input Panel */}
            <div className="w-full md:w-[400px] bg-white border-b md:border-b-0 md:border-r border-gray-200 overflow-y-auto custom-scrollbar p-6 print:hidden shrink-0 h-[45vh] md:h-auto">
                <h2 className="text-lg font-bold text-gray-800 mb-1">
                    {activeTab === 'auto' ? 'AI Generator' : 'Enter Details'}
                </h2>
                <p className="text-xs text-gray-500 mb-6">Create your digital identity card.</p>

                {activeTab === 'auto' && (
                  <div className="bg-gradient-to-br from-purple-50 to-white p-4 rounded-xl border border-purple-100 shadow-sm space-y-3 mb-6">
                    <div className="flex items-center gap-2 text-purple-800 font-bold text-xs uppercase mb-1">
                       <Sparkles size={14} /> Describe Farmer/Agent
                    </div>
                    <textarea 
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      placeholder="e.g. Ramesh Patil from Nashik, Village Niphad, Mobile 98765..."
                      className="w-full p-3 rounded-lg border border-purple-200 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none h-24 bg-white/80"
                    />
                    <button 
                      onClick={handleAutoGenerate}
                      disabled={isLoading || !prompt}
                      className="w-full py-2 bg-purple-600 text-white rounded-lg text-sm font-medium hover:bg-purple-700 disabled:opacity-50 transition-colors flex items-center justify-center gap-2 shadow-sm"
                    >
                      {isLoading ? <RefreshCw className="animate-spin" size={16} /> : "Auto-Fill"}
                    </button>
                  </div>
                )}

                <div className="space-y-5">
                   {/* Photos */}
                   <div className="grid grid-cols-2 gap-4">
                        <div 
                            className="bg-white border-2 border-dashed border-blue-400 rounded-xl p-4 flex flex-col items-center justify-center cursor-pointer hover:bg-blue-50 transition-all text-center h-32"
                            onClick={() => fileInputRef.current?.click()}
                        >
                            {data.photoUrl ? (
                                <img src={data.photoUrl} className="w-full h-full object-contain rounded" />
                            ) : (
                                <>
                                    <Camera size={20} className="text-blue-500 mb-1" />
                                    <span className="text-xs font-bold text-gray-700">Add Photo</span>
                                </>
                            )}
                            <input type="file" ref={fileInputRef} onChange={(e) => handleFileUpload(e, 'photoUrl')} className="hidden" accept="image/*" />
                        </div>

                        <div 
                            className="bg-white border-2 border-dashed border-gray-300 rounded-xl p-4 flex flex-col items-center justify-center cursor-pointer hover:bg-gray-50 transition-all text-center h-32"
                            onClick={() => signatureInputRef.current?.click()}
                        >
                            {data.signatureUrl ? (
                                <img src={data.signatureUrl} className="w-full h-full object-contain rounded" />
                            ) : (
                                <>
                                    <PenTool size={20} className="text-gray-400 mb-1" />
                                    <span className="text-xs font-medium text-gray-600">Signature</span>
                                </>
                            )}
                            <input type="file" ref={signatureInputRef} onChange={(e) => handleFileUpload(e, 'signatureUrl')} className="hidden" accept="image/*" />
                        </div>
                   </div>

                   {/* Core Details */}
                   <div className="space-y-3">
                      <div className="flex items-center gap-2 pb-2 border-b border-gray-100">
                         <div className="w-1 h-4 bg-blue-500 rounded-full"></div>
                         <h3 className="text-xs font-bold text-gray-700 uppercase">Identity Info</h3>
                      </div>
                      
                      {/* RENAMED ID FIELD AS REQUESTED */}
                      <InputGroup label="Former ID / Registration No." name="idNumber" value={data.idNumber} onChange={handleInputChange} placeholder="Required" />
                      
                      <InputGroup label="Full Name" name="name" value={data.name} onChange={handleInputChange} placeholder="Required" />
                      
                      {data.cardType === 'kisan' && (
                        <InputGroup label="Full Name (Regional)" name="hindiName" value={data.hindiName || ''} onChange={handleInputChange} className="font-hindi" />
                      )}
                      
                      <div className="grid grid-cols-2 gap-3">
                          <InputGroup label="Mobile Number" name="phone" value={data.phone} onChange={handleInputChange} />
                          <InputGroup label="DOB" name="dob" value={data.dob} onChange={handleInputChange} />
                      </div>
                   </div>

                   {/* Additional Details based on Type */}
                   {data.cardType === 'kisan' ? (
                      <div className="space-y-3 pt-2">
                          <div className="flex items-center gap-2 pb-2 border-b border-gray-100">
                            <div className="w-1 h-4 bg-green-500 rounded-full"></div>
                            <h3 className="text-xs font-bold text-gray-700 uppercase">Location & Land</h3>
                          </div>
                          <InputGroup label="Full Address" name="address" type="textarea" value={data.address} onChange={handleInputChange} />
                          <div className="grid grid-cols-2 gap-3">
                              <InputGroup label="Village" name="village" value={data.village} onChange={handleInputChange} />
                              <InputGroup label="District" name="district" value={data.district} onChange={handleInputChange} />
                          </div>
                          {/* ADDED MISSING INPUTS FOR GAT NUMBER AND AREA */}
                          <div className="grid grid-cols-2 gap-3">
                              <InputGroup label="Gat Number" name="gatNumber" value={data.gatNumber} onChange={handleInputChange} placeholder="e.g. 34/2" />
                              <InputGroup label="Area (Hectares)" name="area" value={data.area} onChange={handleInputChange} placeholder="e.g. 1.25" />
                          </div>
                      </div>
                   ) : (
                      <div className="space-y-3 pt-2">
                          <div className="flex items-center gap-2 pb-2 border-b border-gray-100">
                            <div className="w-1 h-4 bg-yellow-500 rounded-full"></div>
                            <h3 className="text-xs font-bold text-gray-700 uppercase">Bank Info</h3>
                          </div>
                          <InputGroup label="Full Address" name="address" type="textarea" value={data.address} onChange={handleInputChange} />
                          <InputGroup label="Branch" name="branchName" value={data.branchName || ''} onChange={handleInputChange} />
                      </div>
                   )}
                </div>
            </div>

            {/* Preview Area */}
            <div className="flex-1 bg-gray-100/50 flex flex-col relative overflow-hidden h-full">
               <div className="h-12 border-b border-gray-200 bg-white px-4 flex items-center justify-between print:hidden shrink-0">
                  <span className="text-xs font-bold text-gray-500 uppercase">Live Preview</span>
                  <div className="flex items-center gap-2">
                     <button 
                        onClick={handleDownloadPDF} 
                        disabled={isDownloading || !data.id}
                        className="flex items-center gap-2 px-3 py-1.5 bg-blue-600 text-white rounded text-xs font-bold shadow-sm hover:bg-blue-700 transition-all disabled:opacity-50 disabled:bg-gray-400"
                     >
                        {isDownloading ? <RefreshCw className="animate-spin" size={14} /> : <Download size={14} />}
                        <span className="hidden md:inline">Download PDF</span>
                     </button>
                     <button onClick={() => window.print()} className="flex items-center gap-2 px-3 py-1.5 bg-green-600 text-white rounded text-xs font-bold shadow-sm hover:bg-green-700 transition-all">
                        <Printer size={14} /> <span className="hidden md:inline">Print</span>
                     </button>
                  </div>
               </div>

               <div id="print-container" className="flex-1 overflow-auto custom-scrollbar p-6 flex flex-col items-center gap-8 print:p-0 print:block print:bg-white bg-slate-100">
                  {/* Card Front */}
                  <div id="card-front" className="relative group print:break-inside-avoid print-card-wrapper inline-block shadow-xl">
                      {data.cardType === 'kisan' ? <IdCardFront data={data} /> : <BCAgentCard data={data} />}
                  </div>
                  {/* Card Back */}
                  <div id="card-back" className="relative group print:break-inside-avoid print-card-wrapper inline-block shadow-xl">
                      {data.cardType === 'kisan' ? <IdCardBack data={data} /> : <BCAgentCardBack data={data} />}
                  </div>
                  <div className="h-20"></div>
               </div>
            </div>
        </div>
      </div>
    </div>
  );
}
